### ISSUE TITLE
DOCs what's the spec on single quote key names?

### ISSUE THREAD

**Issue by keyscores** [hjson/hjson-js#14]
I'm guessing this may be an edge case, but I can't see any documentation on handling key names with single quotes vs double quotes.

In JS I would not expect that these two statements yield different results.
```
HJSON.parse('{ "a": 1}')
>{ a: 1 } //this is the expected response.

HJSON.parse("{ 'a': 1}")
> { '\'a\'': 1 } // unexpected
```

Even stranger to me is the behavior of single quotes with whitespace.
```
HJSON.parse('{ "a b": 1}')
>{ 'a b': 1 } // this is the expected response

HJSON.parse("{ 'a b': 1}")
>Error: Found whitespace in your key name (use quotes to include) at line 1,5 >>>{ 'a b': 1}
```

In npm 'relaxed-json' there is no difference between the implementations.

**Comment by keyscores** [comment]
@laktak Any thoughts on this?

**Comment by laktak** [comment]
see https://github.com/hjson/hjson/issues/65
