### ISSUE TITLE
Support commas between elements

### ISSUE THREAD

**Issue by SamVerschueren** [hjson/hjson-js#17]
See https://github.com/hjson/hjson-js/issues/16#issue-195740798.

The output of the stringify call returns key-value pairs without commas. So this is what I get

```json
{
    foo: "bar"
    unicorn: "rainbow"
}
```

This is probably intended. I think it would be nice if there was an option to at least allow commas between elements.

```json
{
    foo: "bar",
    unicorn: "rainbow"
}
```

**Comment by laktak** [comment]
Would you like to do a PR for this as well?

**Comment by SamVerschueren** [comment]
Yes, sure
