### ISSUE TITLE
How do I use options?

### ISSUE THREAD

**Issue by tmamedbekov** [hjson/hjson-js#22]
Can you please explain how to use options on `var text2 = Hjson.stringify(obj);` after everything is being parsed I would like to add quotes to all my original json strings. 

 `var obj = Hjson.parse(output);
  var text2 = Hjson.stringify(obj);`

after this is being done, I get a stripped down code.

**Comment by laktak** [comment]
See the docs [here](https://github.com/hjson/hjson-js#hjsonstringifyvalue-options).

For example `var text2 = Hjson.stringify(obj, { quotes: "strings" });`

**Comment by tmamedbekov** [comment]
yeap yeap already got it going.
`var text2 = Hjson.stringify(obj, {keepWsc: false, bracesSameLine: true, quotes: "strings", quotes: "keys", separator: true});`

**Comment by laktak** [comment]
You can only specify one value for quotes - you probably want `quotes: "all"`

What is not easy to set up? Would a sample help? (it's actually [here](https://github.com/hjson/hjson-js/tree/master/sample) but not mentioned in the README).

**Comment by tmamedbekov** [comment]
That actual string worked for me. I got confused actually with the options. Maybe you could add same sample code to the GH page. Thanks anyways really great tool, helped do a major thing :)
