### ISSUE TITLE
Consider adding -w mode to cli

### ISSUE THREAD

**Issue by qm3ster** [hjson/hjson-js#23]

**Comment by laktak** [comment]
@qm3ster a description would help

**Comment by qm3ster** [comment]
Most conversion/translation libraries, when also shipping a cli interface, include a watch (-w) option, which doesn't quit after conversion, but instead watches the input file for changes and reapplies the conversion every time it's updated. You could use [watch]( https://github.com/mikeal/watch)
At a second glance, I think this would not work with stdout, since you have to rewrite the output file from the beginning, and would require a file output mode. Feel free to close this, and tell me if you'd like a pull request if I ever implement it.
Also, [jstransformer-cli](https://github.com/jstransformers/jstransformer-cli) (there is a jstransformer that uses your library) isn't currently providing that option either.

**Comment by laktak** [comment]
Thanks but as there are lots of tools available that provide this feature I don't want to reimplement it here.
