### ISSUE TITLE
Readable compact format

### ISSUE THREAD

**Issue by nyurik** [hjson/hjson-js#26]
Is there a "compact but readable" format for HJSON?  Something like https://github.com/lydell/json-stringify-pretty-compact for JSON?

Thanks!

**Comment by laktak** [comment]
You are talking about

```
{
  "bool": true,
  "short array": [1, 2, 3],
  "long array": [
    {"x": 1, "y": 2},
    {"x": 2, "y": 1},
    {"x": 1, "y": 1},
    {"x": 2, "y": 2}
  ]
}
```

That would only work for Hjson if none of the elements inside are quoteless strings (they require a new line each).

If it was only allowed in combination with the "quote all strings" option it would probably be easy to implement [here](https://github.com/hjson/hjson-js/blob/master/lib/hjson-stringify.js#L263), otherwise no.

**Comment by nyurik** [comment]
@laktak would it make sense to have a "mixed" approach - if multiple values can fit on the same line, encode them as regular JSON (just like compact json formatter does).  Otherwise, follow HJSON rules

**Comment by laktak** [comment]
Like I said, that won't be *easy* to do. What is your use case? How would you define "fit on the same line"?

**Comment by nyurik** [comment]
@laktak I was hoping to adapt HJSON to [Vega (JSON) editing](https://vega.github.io/editor/#/examples/vega/interactive-legend) -- HJSON should make this code much more readable (BTW, is there a HJSON support for Monaco text editor?). A small set of values in a list should be on the same line -- e.g.  `key: [1, 2, "3", false]`.  Same with a small object:  `key: {"a":1, "b":2}`.

**Comment by laktak** [comment]
After thinking about why this can't work I experimented a bit and found it to be working quite well :) Thanks for the idea! 

You need to call
```
    result = Hjson.stringify(obj, { condense: 60 });
```

Let me know if this works for you.

**Comment by laktak** [comment]
Monaco: see https://marketplace.visualstudio.com/items?itemName=laktak.hjson

**Comment by nyurik** [comment]
@laktak this is an awesome start! Here is an example of a compact( len=65 ) json and hjson representation of a Vega diagram with your new changes.  The compact JSON is still more compact and readable, because the eyes do not stumble on each "{" and "[" that occupies a separate line: https://gist.github.com/nyurik/96ab0d0d19d4c3aee83b0250fbb9335c/revisions

Do you think the initial (not trailing) `[` and `{` can be placed on the same line as `:` ?

Thanks for your hard work!!!

**Comment by laktak** [comment]
Happy to hellp with your project. Looks very cool btw!

There's actually a switch for controlling the braces:

```
    result = Hjson.stringify(obj, { condense: 60, bracesSameLine: true });
```

**Comment by nyurik** [comment]
This is awesome, thanks!!!
