### ISSUE TITLE
TypeScript declarations file

### ISSUE THREAD

**Issue by adamvoss** [hjson/hjson-js#27]
It would be nice if there were a TypeScript definitions file included so that users of supported editors (JS or TS) have completion information.  TypeScript users would benefit further by having type checking information and being able to use hjson in TypeScript projects where strict checking is enabled (which is the default for new projects).

**Comment by laktak** [comment]
Good idea! Would you like to do a PR for this?

**Comment by adamvoss** [comment]
Looks like I won't need to!  @crunchie84 has written them (DefinitelyTyped/DefinitelyTyped#18038) and will hopefully open the PR here.

**Comment by adamvoss** [comment]
Since this have been merged into DefinitelyTyped, I do not see a compelling reason to go bundle the types here and remove them from DT.
